# Site settings
title: freephdlabor
description: Multi-agent system for automated scientific discovery
author: Ed Li
email: ed.li@yale.edu

# Theme - choose one of these popular options:
# Options: minima, cayman, slate, minimal, modernist, midnight, architect, tactile, leap-day, time-machine
theme: minimal

# Optional: Custom colors
# Uncomment and customize if desired
# cayman:
#   primary_color: '#159957'
#   secondary_color: '#155799'

# GitHub repo (for "View on GitHub" button)
github_username: ltjed
repository: freephdlabor/freephdlabor.github.io

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
